// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBrPYjPv-X5iJBpuOb_29EFHIcgKIxZo',
    appId: '1:938957140582:web:d90350263bacdbcf0173a7',
    messagingSenderId: '938957140582',
    projectId: 'prescript-system',
    authDomain: 'prescript-system.firebaseapp.com',
    storageBucket: 'prescript-system.firebasestorage.app',
    measurementId: 'G-9GF376WZC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qjiYs9JAdbTTyaWOqRkhgWeTkYkVi5s',
    appId: '1:938957140582:android:107b4647ff4ddaa30173a7',
    messagingSenderId: '938957140582',
    projectId: 'prescript-system',
    storageBucket: 'prescript-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZbWAKUqdpBX36dkVXkSEarwCXpgP_Is',
    appId: '1:938957140582:ios:94a8774554ebcf080173a7',
    messagingSenderId: '938957140582',
    projectId: 'prescript-system',
    storageBucket: 'prescript-system.firebasestorage.app',
    iosBundleId: 'com.example.prescript',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZbWAKUqdpBX36dkVXkSEarwCXpgP_Is',
    appId: '1:938957140582:ios:94a8774554ebcf080173a7',
    messagingSenderId: '938957140582',
    projectId: 'prescript-system',
    storageBucket: 'prescript-system.firebasestorage.app',
    iosBundleId: 'com.example.prescript',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsBrPYjPv-X5iJBpuOb_29EFHIcgKIxZo',
    appId: '1:938957140582:web:582736f1a71475780173a7',
    messagingSenderId: '938957140582',
    projectId: 'prescript-system',
    authDomain: 'prescript-system.firebaseapp.com',
    storageBucket: 'prescript-system.firebasestorage.app',
    measurementId: 'G-KJ1HWSSLTT',
  );
}
